name: Publish the Docker image

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build testing the Docker image (php-base:8.2.1)
        run: docker build . --file /home/runner/work/php-base/php-base/dockerfile/8.2.1/Dockerfile --tag test/php-base:8.2.1
